# Generated by Django 4.2.1 on 2026-04-19 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='task',
            name='support',
        ),
        migrations.AddField(
            model_name='task',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
