# Generated by Django 4.2.1 on 2026-04-20 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('unconfirm', 'Unconfirm'), ('pause', 'Pause'), ('done', 'Done')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskimage',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.task'),
        ),
    ]
